services:
  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es5c-users:latest
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb
    env_file:
      - .env

  gatewayservice:
    build: ./gatewayservice
    container_name: gatewayservice
    image: ghcr.io/arquisoft/yovi_es5c-gateway-service:latest
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://users:3000
      - GAMEY_SERVICE_URL=http://gamey:4000
    depends_on:
      - users
      - gamey
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:8000 
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es5c-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - gatewayservice
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es5c-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mongodb_data: