ifndef::imagesdir[:imagesdir: ../images]

[[section-tests-annex]]
== Anexo: Pruebas de la aplicación

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Descripción general de la estrategia de pruebas y los resultados obtenidos en los distintos niveles de validación (unitarias, integración, E2E y carga).

.Motivation
Garantizar que el sistema cumple con las especificaciones técnicas, funcionales y los requisitos de calidad definidos previamente.

.Form
Resúmenes de ejecución, tablas de cobertura o referencias a informes generados por las herramientas de CI/CD.
****
endif::arc42help[]

=== Estrategia de Pruebas

=== Pruebas Unitarias

=== Pruebas de Integración (E2E)

=== Pruebas de Carga y Rendimiento
Se han realizado pruebas de carga sobre la aplicación desplegada en Azure.

El objetivo de las mismas es comprobar la robustez y resiliencia de la infraestructura que será utilizada por los usuarios reales. 

==== Implementación
Se utiliza Gatling para la ejecución de las pruebas de carga. Para ello se crean como recursos un .csv con los usuarios que serán inyectados para probar, y un escenario donde se especificará la forma de inyectarlos y las acciones que realizarán los mismos. 

Los tests se han ejecutado desde una máquina local con Java 17 y Maven.

Al orquestar las pruebas con Maven, se añaden las dependencias de gatling y otras necesarias a un pom.xml

==== Escenario probado
El escenario que se prueba es el flujo que siguen los usuarios al interactuar con la web:

1. Inicio de sesión
2. Se inicia una partida y se hace un movimiento en el tablero
3. Se consulta el historial de partidas del usuario
4. Se cierra sesión

Se detalla en SimpleFlowSimulation.scala.

==== Carga probada
Se ha planteado una carga que se adapte a las restricciones frente a seguridad implementadas en el gateway (máximo de 500 peticiones por usuario en un minuto).

De este modo: 
- Se cargan 

==== Resultados

=== Pruebas de Usabilidad

Se realizaron pruebas de usabilidad con usuarios de diferentes edades y niveles tecnológicos para evaluar el tiempo que tardaban en completar dos tareas: jugar una partida y consultar el historial.

En la tarea de “jugar una partida”, se observó que los usuarios más jóvenes y con mayor nivel tecnológico completaban la acción más rápidamente (50 segundos), mientras que los usuarios de mayor edad o con menor nivel tecnológico tardan más tiempo (hasta 120 segundos). Esto indicó que la funcionalidad no era igual de intuitiva para todos los perfiles de usuario, especialmente para aquellos menos familiarizados con la tecnología.

En cambio, en la tarea de “consultar el historial”, los tiempos fueron significativamente menores en todos los casos (entre 2 y 12 segundos), lo que sugirió que esta funcionalidad era más clara, accesible y fácil de usar independientemente del perfil del usuario.

A partir de los resultados obtenidos en las pruebas de usabilidad, se realizaron varias mejoras en la aplicación. En primer lugar, modificó el botón de como jugar, ya que, aunque a nosotros nos parecía bastante intuitivo con el icono "?", los usuarios de prueba no identificaban para que servía.

Además, se mejoró la claridad de la interfaz, aumentando el tamaño de letra y mejorando los contrastes para que le resultase más fácil de leer a aquellos usuarios de mayor edad.



ifdef::arc42help[]
[role="arc42help"]
****
.Nota
Relacionar esta sección con los escenarios de calidad definidos en la sección 10 (Sección de Requisitos de Calidad).
****
endif::arc42help[]
