{
 "title": "Monitoring 24h",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(http_request_duration_seconds_count, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_request_duration_seconds_count[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tráfico última hora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_request_duration_seconds_count[1m])))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Requests for $path",
   "type": "timeseries",
   "description": "A partir de la variable, se puede observar para cada endpoint el tráfico del último día.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(\r\n  increase(http_request_duration_seconds_count{path=\"$path\"}[1h])\r\n))",
     "legendFormat": "{{$path}}"
    }
   ]
  },
  {
   "title": "Errores por horas en el último día",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "round(sum(\r\n  increase(http_request_duration_seconds_count{status_code=~\"4..|5..\"}[1h])\r\n))",
     "legendFormat": "Errores"
    }
   ]
  },
  {
   "title": "Average latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[$__interval]))\r\n/\r\nsum(rate(http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "latencia media"
    }
   ]
  }
 ]
}
{
 "title": "Monitoring  last 15min",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latencia p95",
   "type": "stat",
   "description": "El 95% de peticiones tarda menos de este valor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    rate(http_request_duration_seconds_bucket[$__interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request / segundo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Velocidad de request",
   "type": "timeseries",
   "description": "Miramos la velocidad de crecimiento por segundo en las request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}